version: '3'
services:
  service-worker:
    build:
      context: .
      dockerfile: "Dockerfile"
    env_file:
    - build.env
    volumes:
      - "build:/build"
volumes:
  build:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${PWD}/build"